### ISSUE TITLE
Empty token....even if I have one valid

### ISSUE THREAD

**Issue by Maks2615** [selesnow/rtgstat#1]
Good day, Mr.Seleznov, this simple code from the example give me the "Empty token" error, even if I have already one.

> library(rtgstat)
> tg_auth("9999......................9") # my token from the personal cabin
√ API token was set success!
> tg_set_channel_id('t.me/Uybozors')
i Set CHANNEL ID: t.me/Uybozors
> tg_channel_stat()
Error: empty_token

**Comment by selesnow** [comment]
Здравствуйте, т.к. ваш канал русскоязычный то, думаю нам проще будет на русском общаться.

Какая версия пакета у вас установлена? В данный момент я рекомендую поставить версию с гитхаба `0.2.1.9000`.

**Comment by Maks2615** [comment]
здравствуйте, именно эта версия стоит, устанавливал с гитхаба. писал на сайт (https://tgstat.ru/) относительно этой проблемы, они посоветовали обратиться к автору пакета..то есть Вам)
данный канал (Uybozors) - там на узбекском языке на кириллице

**Comment by selesnow** [comment]
Верно, поддержкой пакета я занимаюсь, и вы правы есть ошибка при инициализации токена функцией tg_auth(), исправлю в ближайшее время, а пока можете использовать для установки токена переменную среды.

Пример:

```r
Sys.setenv('TG_API_TOKEN' = '99....9999999')
```

По идее этот подход должен сработать, либо опцией `tg.api_token`

**Comment by selesnow** [comment]
Даже лучше опцией установить

```r
options(tg.api_token = "999999999")
```

Это точно должно сработать, а после отпуска я внесу правки в сам пакет, в начале февраля

**Comment by Maks2615** [comment]
Алексей спасибо большое за поддержку, и в целом, за вклад в библиотеки на R! 
Хорошего Вам отпуска 😊

**Comment by selesnow** [comment]
Попробуйте установку опции, и напишите всё ли получилось.

Тикет пока закрывать не буду, пока пакет не доработаю

**Comment by Maks2615** [comment]
да, спасибо, с опцией сработало

**Comment by selesnow** [comment]
В версию на GitHub уже внёс исправления, в феврале на CRAN закину тоже

**Comment by selesnow** [comment]
Доработка внедрена в версии 0.3.0, которая уже доступна для установки с CRAN.
